version: '3.8'

services:
  mysql-master:
    container_name: mysql-master
    image: mysql:8.0.35
    volumes:
      - ./mysqlrs/master-data:/var/lib/mysql
      - ./mysqlrs/master-log:/var/log/mysql
      - ./config/master:/etc/mysql/conf.d
    networks:
      - mysqlrs-network
    ports:
      - 3307:3306
    links:
      - mysql-slave
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  mysql-slave:
    container_name: mysql-slave
    image: mysql:8.0.35
    volumes:
      - ./mysqlrs/slave-data:/var/lib/mysql
      - ./mysqlrs/slave-log:/var/log/mysql
      - ./config/slave:/etc/mysql/conf.d
    networks:
      - mysqlrs-network
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always

networks:
  mysqlrs-network:
    driver: bridge