global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3600s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'cqvnno1@gmail.com'
    from: 'vn2021no1@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'vn2021no1@gmail.com'
    auth_identity: 'vn2021no1@gmail.com'
    auth_password: 'VN2020NO1@123456'